### ISSUE TITLE
Quotes should not be escaped

### ISSUE THREAD

**Issue by oscarlevin** [skiadas/md2ptx#2]
When I tested, a string like `the "word" is quoted` got translated like `the &amp;&quot;word&quot;&amp is quoted` (although I might have the second escaped characters backward).  Instead it should become `the <q>word</q> is quoted`.

**Comment by skiadas** [comment]
Hm I suspect the challenge would be detecting this case over a case of a lonely quote character. I suspect for example that something like:  `\`"\`` should become `<code>"</code>`. But the current version feels wrong anyway.
Perhaps look for a space to precede it, then look for a matching close? I'm thinking that looking for a preceding space is the most reasonable heuristic.
A similar problem with single quote in something like `can't`.

I think as a first step I might replace the amped-quot part with normal quotes, then look for a space-preceded quote and its partner.

**Comment by skiadas** [comment]
@oscarlevin See if this addresses your use-cases.

**Comment by oscarlevin** [comment]
Yes, I think that does it!
