### ISSUE TITLE
Possibility of using unified and mdast?

### ISSUE THREAD

**Issue by oscarlevin** [skiadas/md2ptx#3]
Just wanted to throw it out there that I'm going to be trying to use the unified framework for translating LaTeX to pretext.  Assuming that I am successful, that would probably make converting other unist format conversions easy.  So the workflow would be to parse markdown to a mdast, then convert the AST to a xast with proper pretext elements and attributes, and then stringify the resulting xast.  The first and third steps are automatic, and the middle step would be very similar to what would happen for translating a latex-AST to xast.

Whether I can figure out how to do the middle step is yet to be seen.

**Comment by skiadas** [comment]
That sounds promising! Does there need to be a more specialized version for xast for PreTeXt, or would there be any benefits to such a thing?

**Comment by oscarlevin** [comment]
That's a good question.  I'm not sure yet whether there would be benefits.  I'm curious whether other XML specifications have done anything like this (well, other than HTML, obviously).

**Comment by skiadas** [comment]
@oscarlevin I made a fair bit of progress on this in #5. brought it to a point where it should be able to replace the old implementation. If you have some time to test it out that would be great!

From the point of view of benefiting from the unified infrastructure:

We can create plugins that operate on xast and perform various operations. For now I have one in https://github.com/skiadas/md2ptx/blob/unified/src/xml-stringify.ts which simply turns the xml into a string (apparently it didn't already exist as a plugin as far as I could tell but maybe I missed something), one in https://github.com/skiadas/md2ptx/blob/unified/src/replace-quotes.ts  which replaces quote pairs with the corresponding tags, and one in https://github.com/skiadas/md2ptx/blob/unified/src/fix-lists.ts which merges a list to its preceding list (and maybe in the future will do other things like remove if possible the paragraph tag within a list item). Any other converter that arrives at a pretext-specific xast tree should be able to make use of them. I can see value in creating more of these that manipulate the xast. At the very least it should be possible to incorporate a formatter (https://github.com/rehypejs/rehype-format is doing something similar but I haven't looked too closely), but I imagine a number of transformations would be possible.

I see value in establishing types for pretext-specific trees, whether somehow as a subset of xast or preferably on their own. The conversion from ptxast to xast should be pretty straightforward, but I think the tooling would benefit from a dedicated ast. But that's perhaps a bigger job.

Regardless, I think it would be nice to at least have a "ptx-validator" plugin, though I'm not sure how much work might be involved in that.

**Comment by oscarlevin** [comment]
Yay!  This is very exciting.  I've been playing with [unified-latex](https://github.com/siefkenj/unified-latex), which includes "to-pretext" support already (although it needs some additional environment support) and it is working really well.  It was very easy to add it to `pretext-tools`.  

I believe that [xast-util-to-xml](https://github.com/syntax-tree/xast-util-to-xml) does the xast to string conversion, and has some plugins for dealing with formatting.  I need to look into this a little more; the unified-latex packages currently just give me back a long string of xml which I passed through the pretext-tools formatter.  But manipulating the AST might be much easier and more robust.  

And yes, figuring out how to use this for validation would be amazing.  Not just for us: I think there is a real need for a non-java relaxng validator for xml.

**Comment by skiadas** [comment]
> I believe that [xast-util-to-xml](https://github.com/syntax-tree/xast-util-to-xml) does the xast to string conversion, and has some plugins for dealing with formatting. I need to look into this a little more; the unified-latex packages currently just give me back a long string of xml which I passed through the pretext-tools formatter. But manipulating the AST might be much easier and more robust.

Yeah that xast-util-to-xml is what I use behind the scenes, but for some obscure reason they haven't offered it as a "compiler-setting plugin", so you can't add it as a step in a pipeline that ends with `.process`. So all my xml-stringify does is basically turn the `toXml` provided by that package into a plugin you can add to a pipeline with `.use(...)`.
